AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/**/*

Documentation:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false
