language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler --no-document
gemfile:
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.7.gemfile
  - gemfiles/rails_5.2.3.gemfile
  - gemfiles/rails_6.0.0.gemfile
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
matrix:
  exclude:
    - gemfile: gemfiles/rails_6.0.0.gemfile
      rvm: 2.4.9
  allow_failures:
    - rvm: ruby-head
